---
title: "Pokémon"
author: "Kroeze & Smink"
date: "12/19/2019"
output: html_document
---

# Introduction

Ever since Ash Ketchum left his home Pallet Town to become a Pokémon Master, aspiring Pokémon trainers from around the world wondered: ``_what is the best Pokémon_’’. Although Ash’s Pikachu is perhaps the most famous Pokémon (even to those less enthusiastic about Pokémon), it is not the _best_. But then who is? 

Although a simple question, from a scientific viewpoint, the question actually requires a more nuanced answer. For example, the first question that an aspiring Pokémon trainer is confronted with, is _which starter Pokémon should I choose_. With the recent release of the 8^th generation, each iteration of new Pokémon presents the player with a choice between a Pokémon of the _water_, _fire_, or _grass_ type. In this interpretation, the _best_ Pokémon boils down to a choice between which of the three starter Pokémon is the _best_ choice.

# Method

We present the results of several simulation-studies.

## Best starter Pokémon

Our first simulation-study aims to answer the question, which starter Pokémon is the superior of the three. With an answer for each of the eight generations of Pokémon, our second simulation-study aims answers the question which of the overall starters is the best choice.

### Exclusions
Only the starting level (5) will be considered.
Weather will not be considered.
Healing and other base stat increasing items will not be considered.
Only first generation rules, pokemon and their stats will be considered.

### Definition of 'best'
The pokemon with the highest average win percentage. While pokemon that excel in their particular niche might be preferable in a team composition, for this first study we only consider individual winrates.

### Simulating battles
Pokemon battles will be simulated using, as far as is practical, the rules and mechanics of the official game. Moves are selected based on.....  

 - best against type? 
 - use defensive/debuff/buff moves?
 - use a fixed pattern/rule of thumb for move repetitions?
 - develop a self-learning neural network?
 
Some resources already exist under an MIT license: https://github.com/fonse/pokemon-battle for simplified simulation of pokemon battles, and https://github.com/pvpoke/pvpoke for more in depth simulation of pokemon _GO_ battles, which are somehow different. 